import 'package:freezed_annotation/freezed_annotation.dart';
import 'ast_node.dart';

part 'screen_definition.freezed.dart';
part 'screen_definition.g.dart';

/// Defines a screen to be generated by Syntaxify.
///
/// Create instances of this class in `.screen.dart` files:
/// ```dart
/// final loginScreen = ScreenDefinition(
///   id: 'login',
///   layout: AstNode.column(children: [
///     AstNode.text(text: 'Welcome'),
///     AstNode.button(label: 'Login', onPressed: 'handleLogin'),
///   ]),
/// );
/// ```
@freezed
class ScreenDefinition with _$ScreenDefinition {
  const factory ScreenDefinition({
    required String id,
    required AstNode layout,
    AppBarNode? appBar,
    String? padding, // Token
  }) = _ScreenDefinition;

  factory ScreenDefinition.fromJson(Map<String, dynamic> json) =>
      _$ScreenDefinitionFromJson(json);
}
