import 'package:freezed_annotation/freezed_annotation.dart';
import 'layout_node.dart';

part 'screen_definition.freezed.dart';
part 'screen_definition.g.dart';

/// Defines a screen to be generated by Syntaxify.
///
/// Create instances of this class in `.screen.dart` files:
/// ```dart
/// final loginScreen = ScreenDefinition(
///   layout: App.column(children: [
///     App.text(text: 'Welcome'),
///     App.button(label: 'Login', onPressed: 'handleLogin'),
///   ]),
/// );
/// ```
///
/// The `id` is optional - if not provided, it will be inferred from the
/// variable name (e.g., `loginScreen` → id: 'loginScreen').
@freezed
sealed class ScreenDefinition with _$ScreenDefinition {
  const factory ScreenDefinition({
    /// Screen identifier. If not provided, inferred from variable name.
    @Default('') String id,
    required App layout,
    App? appBar,
    String? padding, // Token
  }) = _ScreenDefinition;

  factory ScreenDefinition.fromJson(Map<String, dynamic> json) =>
      _$ScreenDefinitionFromJson(json);
}
