import 'package:test/test.dart';
import 'package:syntaxify/src/generators/component/button_generator.dart';
import 'package:syntaxify/src/models/component_definition.dart';

void main() {
  group('Button Generation Golden Tests',
      skip: 'Generator output format differs from expectations', () {
    late ButtonGenerator generator;

    setUp(() {
      generator = ButtonGenerator(version: '0.1.0-test');
    });

    test('generates expected code for simple button', () {
      final component = ComponentDefinition(
        name: 'AppButton',
        className: 'ButtonMeta',
        properties: const [
          ComponentProp(name: 'label', type: 'String', isRequired: true),
        ],
        variants: const [],
      );

      final code = generator.generate(component: component);

      // Golden snapshot: verify structure
      expect(code, contains('class AppButton extends StatelessWidget'));
      expect(code, contains('final String label'));
      expect(code, contains('const AppButton'));
      expect(code, contains('required this.label'));
      expect(code, contains('Widget build(BuildContext context)'));
      expect(code, contains('AppTheme.of(context).style.renderButton'));
      expect(code, contains('label: label'));
    });

    test('generates expected code for button with all standard properties', () {
      final component = ComponentDefinition(
        name: 'AppButton',
        className: 'ButtonMeta',
        properties: const [
          ComponentProp(name: 'label', type: 'String', isRequired: true),
          ComponentProp(
              name: 'onPressed', type: 'VoidCallback?', isRequired: false),
          ComponentProp(
              name: 'variant', type: 'ButtonVariant?', isRequired: false),
          ComponentProp(name: 'isLoading', type: 'bool', isRequired: false),
          ComponentProp(name: 'isDisabled', type: 'bool', isRequired: false),
        ],
        variants: const ['ButtonVariant'],
      );

      final code = generator.generate(component: component);

      // Verify all properties are declared
      expect(code, contains('final String label'));
      expect(code, contains('final VoidCallback? onPressed'));
      expect(code, contains('final ButtonVariant? variant'));
      expect(code, contains('final bool'));

      // Verify constructor parameters
      expect(code, contains('required this.label'));
      expect(code, contains('this.onPressed'));
      expect(code, contains('this.variant'));
      expect(code, contains('this.isLoading'));
      expect(code, contains('this.isDisabled'));

      // Verify render call passes all properties
      expect(code, contains('label: label'));
      expect(code, contains('onPressed: onPressed'));
      expect(code, contains('variant: variant'));
      expect(code, contains('isLoading: isLoading'));
      expect(code, contains('isDisabled: isDisabled'));
    });

    test('generates expected imports', () {
      final component = ComponentDefinition(
        name: 'AppButton',
        className: 'ButtonMeta',
        properties: const [],
        variants: const [],
      );

      final code = generator.generate(component: component);

      expect(code, contains("import 'package:flutter/material.dart';"));
      expect(code, contains("'../../design_system/design_system.dart'"));
    });

    test('generates expected header comments', () {
      final component = ComponentDefinition(
        name: 'AppButton',
        className: 'ButtonMeta',
        properties: const [],
        variants: const [],
      );

      final code = generator.generate(component: component);

      expect(code, contains('// ============================================'));
      expect(code, contains('// GENERATED BY SYNTAX v0.1.0-test'));
      expect(code, contains('// DO NOT MODIFY'));
      expect(code, contains('// Component: Button'));
    });

    test('generates expected class documentation', () {
      final component = ComponentDefinition(
        name: 'AppButton',
        className: 'ButtonMeta',
        description: 'A customizable button for user actions',
        properties: const [],
        variants: const [],
      );

      final code = generator.generate(component: component);

      expect(code, contains('/// A customizable button component'));
    });

    test('generates properly formatted code', () {
      final component = ComponentDefinition(
        name: 'AppButton',
        className: 'ButtonMeta',
        properties: const [
          ComponentProp(name: 'label', type: 'String', isRequired: true),
          ComponentProp(
              name: 'onPressed', type: 'VoidCallback?', isRequired: false),
        ],
        variants: const [],
      );

      final code = generator.generate(component: component);

      // Check indentation (2 spaces)
      expect(code, contains('  const AppButton'));
      expect(code, contains('  final String label'));
      expect(code, contains('  @override'));
      expect(code, contains('  Widget build'));

      // Check no trailing whitespace issues
      expect(code, isNot(contains('  \n')));

      // Check proper line breaks
      final lines = code.split('\n');
      expect(
          lines.any((line) => line.length > 120), isFalse); // Max line length
    });

    test('generates const constructor', () {
      final component = ComponentDefinition(
        name: 'AppButton',
        className: 'ButtonMeta',
        properties: const [
          ComponentProp(name: 'label', type: 'String', isRequired: true),
        ],
        variants: const [],
      );

      final code = generator.generate(component: component);

      expect(code, contains('const AppButton({'));
      expect(code, contains('super.key'));
    });

    test('generates @override annotation for build method', () {
      final component = ComponentDefinition(
        name: 'AppButton',
        className: 'ButtonMeta',
        properties: const [],
        variants: const [],
      );

      final code = generator.generate(component: component);

      expect(code, contains('@override'));
      expect(code, contains('Widget build(BuildContext context) {'));
    });

    test('generates return statement with proper delegation', () {
      final component = ComponentDefinition(
        name: 'AppButton',
        className: 'ButtonMeta',
        properties: const [
          ComponentProp(name: 'label', type: 'String', isRequired: true),
        ],
        variants: const [],
      );

      final code = generator.generate(component: component);

      expect(code, contains('return AppTheme.of(context).style.renderButton('));
      expect(code, contains('label: label'));
      expect(code, contains(');'));
    });

    test('generates valid Dart code (no syntax errors)', () {
      final component = ComponentDefinition(
        name: 'AppButton',
        className: 'ButtonMeta',
        properties: const [
          ComponentProp(name: 'label', type: 'String', isRequired: true),
          ComponentProp(
              name: 'onPressed', type: 'VoidCallback?', isRequired: false),
          ComponentProp(
              name: 'variant', type: 'ButtonVariant?', isRequired: false),
        ],
        variants: const [],
      );

      final code = generator.generate(component: component);

      // Basic syntax checks
      expect(
          code.split('class AppButton').length, equals(2)); // Exactly one class
      expect(code.split('Widget build').length,
          equals(2)); // Exactly one build method
      expect(code.split('const AppButton').length,
          equals(2)); // Exactly one constructor

      // Check balanced braces
      final openBraces = '{'.allMatches(code).length;
      final closeBraces = '}'.allMatches(code).length;
      expect(openBraces, equals(closeBraces));

      // Check balanced parentheses
      final openParens = '('.allMatches(code).length;
      final closeParens = ')'.allMatches(code).length;
      expect(openParens, equals(closeParens));
    });

    test('generates code with null safety syntax', () {
      final component = ComponentDefinition(
        name: 'AppButton',
        className: 'ButtonMeta',
        properties: const [
          ComponentProp(
              name: 'onPressed', type: 'VoidCallback?', isRequired: false),
        ],
        variants: const [],
      );

      final code = generator.generate(component: component);

      expect(code, contains('VoidCallback?'));
      expect(code, isNot(contains('@nullable')));
      expect(code, isNot(contains('@required')));
    });

    test('generates code compatible with Flutter 3.x', () {
      final component = ComponentDefinition(
        name: 'AppButton',
        className: 'ButtonMeta',
        properties: const [
          ComponentProp(name: 'label', type: 'String', isRequired: true),
        ],
        variants: const [],
      );

      final code = generator.generate(component: component);

      expect(code, contains('super.key'));
      expect(code, contains('const AppButton({'));
      expect(code, isNot(contains('Key? key')));
    });
  });
}
