import 'package:code_builder/code_builder.dart';
import 'package:dart_style/dart_style.dart';
import 'package:syntaxify/src/utils/string_utils.dart';

/// Generates enum files from component variant definitions.
///
/// Creates enum files like `button_variant.dart` containing:
/// ```dart
/// enum ButtonVariant { primary, secondary, outlined, text }
/// ```
class EnumGenerator {
  final DartFormatter _formatter =
      DartFormatter(languageVersion: DartFormatter.latestLanguageVersion);

  /// Generate enum code for a component.
  ///
  /// [componentName] - The component name (e.g., 'Button', 'Text')
  /// [variants] - List of variant values (e.g., ['primary', 'secondary'])
  ///
  /// Returns formatted Dart code for the enum.
  String generate(String componentName, List<String> variants) {
    if (variants.isEmpty) {
      throw ArgumentError('Variants list cannot be empty');
    }

    // componentName is already in PascalCase (e.g., 'Button', 'AppBar')
    final enumName = '${componentName}Variant';

    final enumSpec = Enum((b) => b
      ..name = enumName
      ..docs.add('/// Variants for $componentName component.')
      ..docs.add('///')
      ..docs.add('/// Generated by Syntaxify. Do not modify by hand.')
      ..values.addAll(
        variants.map(
          (v) => EnumValue((vb) => vb..name = v),
        ),
      ));

    final library = Library((b) => b
      ..comments.add('// GENERATED CODE - DO NOT MODIFY BY HAND')
      ..comments.add('// Generated by Syntaxify EnumGenerator')
      ..body.add(enumSpec));

    final emitter = DartEmitter(useNullSafetySyntax: true);
    final code = library.accept(emitter).toString();

    return _formatter.format(code);
  }
}
