import 'package:test/test.dart';
import 'package:syntaxify/src/generators/component/button_generator.dart';
import 'package:syntaxify/src/models/component_definition.dart';
import 'package:syntaxify/src/models/component_prop.dart';

void main() {
  group('ButtonGenerator', () {
    late ButtonGenerator generator;

    setUp(() {
      generator = ButtonGenerator();
    });

    group('canHandle', () {
      test('returns true for button component', () {
        final component = ComponentDefinition(
          name: 'AppButton',
          className: 'ButtonMeta',
          properties: const [],
          variants: const [],
        );

        expect(generator.canHandle(component), isTrue);
      });

      test('returns true for Button component without App prefix', () {
        final component = ComponentDefinition(
          name: 'Button',
          className: 'ButtonMeta',
          properties: const [],
          variants: const [],
        );

        expect(generator.canHandle(component), isTrue);
      });

      test('returns false for non-button component', () {
        final component = ComponentDefinition(
          name: 'AppText',
          className: 'TextMeta',
          properties: const [],
          variants: const [],
        );

        expect(generator.canHandle(component), isFalse);
      });

      test('returns false for input component', () {
        final component = ComponentDefinition(
          name: 'AppInput',
          className: 'InputMeta',
          properties: const [],
          variants: const [],
        );

        expect(generator.canHandle(component), isFalse);
      });
    });

    group('generate', () {
      test('generates valid Dart code', () {
        final component = ComponentDefinition(
          name: 'AppButton',
          className: 'ButtonMeta',
          properties: const [
            ComponentProp(name: 'label', type: 'String', isRequired: true),
          ],
          variants: const [],
        );

        final code = generator.generate(component: component);

        expect(code, isNotEmpty);
        expect(code, contains('class AppButton'));
        expect(code, contains('extends StatelessWidget'));
      });

      test('includes imports', () {
        final component = ComponentDefinition(
          name: 'AppButton',
          className: 'ButtonMeta',
          properties: const [],
          variants: const [],
        );

        final code = generator.generate(component: component);

        expect(code, contains('import \'package:flutter/material.dart\''));
        expect(code, contains('design_system/design_system.dart'));
      });

      test('generates header comments', () {
        final component = ComponentDefinition(
          name: 'AppButton',
          className: 'ButtonMeta',
          properties: const [],
          variants: const [],
        );

        final code = generator.generate(component: component);

        expect(code, contains('GENERATED BY SYNTAX'));
        expect(code, contains('DO NOT MODIFY'));
      });

      test('generates constructor with required parameters', () {
        final component = ComponentDefinition(
          name: 'AppButton',
          className: 'ButtonMeta',
          properties: const [
            ComponentProp(name: 'label', type: 'String', isRequired: true),
            ComponentProp(name: 'variant', type: 'ButtonVariant?', isRequired: false),
          ],
          variants: const [],
        );

        final code = generator.generate(component: component);

        expect(code, contains('const AppButton'));
        expect(code, contains('required this.label'));
        expect(code, contains('this.variant'));
      });

      test('generates field declarations', () {
        final component = ComponentDefinition(
          name: 'AppButton',
          className: 'ButtonMeta',
          properties: const [
            ComponentProp(name: 'label', type: 'String', isRequired: true),
            ComponentProp(name: 'onPressed', type: 'VoidCallback?', isRequired: false),
          ],
          variants: const [],
        );

        final code = generator.generate(component: component);

        expect(code, contains('final String label'));
        expect(code, contains('final VoidCallback? onPressed'));
      });

      test('generates build method that delegates to style', () {
        final component = ComponentDefinition(
          name: 'AppButton',
          className: 'ButtonMeta',
          properties: const [
            ComponentProp(name: 'label', type: 'String', isRequired: true),
          ],
          variants: const [],
        );

        final code = generator.generate(component: component);

        expect(code, contains('Widget build(BuildContext context)'));
        expect(code, contains('AppTheme.of(context)'));
        expect(code, contains('.style.renderButton'));
        expect(code, contains('return'));
      });

      test('passes all properties to render method', () {
        final component = ComponentDefinition(
          name: 'AppButton',
          className: 'ButtonMeta',
          properties: const [
            ComponentProp(name: 'label', type: 'String', isRequired: true),
            ComponentProp(name: 'onPressed', type: 'VoidCallback?', isRequired: false),
            ComponentProp(name: 'variant', type: 'ButtonVariant?', isRequired: false),
            ComponentProp(name: 'isLoading', type: 'bool', isRequired: false),
          ],
          variants: const [],
        );

        final code = generator.generate(component: component);

        expect(code, contains('label: label'));
        expect(code, contains('onPressed: onPressed'));
        expect(code, contains('variant: variant'));
        expect(code, contains('isLoading: isLoading'));
      });

      test('generates documentation comment', () {
        final component = ComponentDefinition(
          name: 'AppButton',
          className: 'ButtonMeta',
          description: 'A customizable button for user actions',
          properties: const [],
          variants: const [],
        );

        final code = generator.generate(component: component);

        expect(code, contains('///'));
        expect(code, contains('button'));
      });

      test('formats code properly', () {
        final component = ComponentDefinition(
          name: 'AppButton',
          className: 'ButtonMeta',
          properties: const [
            ComponentProp(name: 'label', type: 'String', isRequired: true),
          ],
          variants: const [],
        );

        final code = generator.generate(component: component);

        // Check proper indentation and formatting
        expect(code, contains('  @override'));
        expect(code, contains('  Widget build'));
        expect(code, contains('    return'));
      });

      test('handles boolean properties', () {
        final component = ComponentDefinition(
          name: 'AppButton',
          className: 'ButtonMeta',
          properties: const [
            ComponentProp(name: 'label', type: 'String', isRequired: true),
            ComponentProp(name: 'isLoading', type: 'bool', isRequired: false),
            ComponentProp(name: 'isDisabled', type: 'bool', isRequired: false),
          ],
          variants: const [],
        );

        final code = generator.generate(component: component);

        expect(code, contains('final bool'));
        expect(code, contains('isLoading'));
        expect(code, contains('isDisabled'));
      });

      test('handles optional callback properties', () {
        final component = ComponentDefinition(
          name: 'AppButton',
          className: 'ButtonMeta',
          properties: const [
            ComponentProp(name: 'label', type: 'String', isRequired: true),
            ComponentProp(name: 'onPressed', type: 'VoidCallback?', isRequired: false),
            ComponentProp(name: 'onLongPress', type: 'VoidCallback?', isRequired: false),
          ],
          variants: const [],
        );

        final code = generator.generate(component: component);

        expect(code, contains('VoidCallback? onPressed'));
        expect(code, contains('VoidCallback? onLongPress'));
      });

      test('handles variant enum properties', () {
        final component = ComponentDefinition(
          name: 'AppButton',
          className: 'ButtonMeta',
          properties: const [
            ComponentProp(name: 'label', type: 'String', isRequired: true),
            ComponentProp(name: 'variant', type: 'ButtonVariant?', isRequired: false),
          ],
          variants: const ['ButtonVariant'],
        );

        final code = generator.generate(component: component);

        expect(code, contains('ButtonVariant'));
        expect(code, contains('variant'));
      });

      test('generates const constructor', () {
        final component = ComponentDefinition(
          name: 'AppButton',
          className: 'ButtonMeta',
          properties: const [],
          variants: const [],
        );

        final code = generator.generate(component: component);

        expect(code, contains('const AppButton'));
      });

      test('includes super.key parameter', () {
        final component = ComponentDefinition(
          name: 'AppButton',
          className: 'ButtonMeta',
          properties: const [],
          variants: const [],
        );

        final code = generator.generate(component: component);

        expect(code, contains('super.key'));
      });

      test('handles component with many properties', () {
        final component = ComponentDefinition(
          name: 'AppButton',
          className: 'ButtonMeta',
          properties: const [
            ComponentProp(name: 'label', type: 'String', isRequired: true),
            ComponentProp(name: 'onPressed', type: 'VoidCallback?', isRequired: false),
            ComponentProp(name: 'variant', type: 'ButtonVariant?', isRequired: false),
            ComponentProp(name: 'isLoading', type: 'bool', isRequired: false),
            ComponentProp(name: 'isDisabled', type: 'bool', isRequired: false),
            ComponentProp(name: 'icon', type: 'IconData?', isRequired: false),
          ],
          variants: const [],
        );

        final code = generator.generate(component: component);

        expect(code, contains('final String label'));
        expect(code, contains('final VoidCallback? onPressed'));
        expect(code, contains('final ButtonVariant? variant'));
        expect(code, contains('final bool'));
        expect(code, contains('final IconData? icon'));
      });

      test('generates compilable Dart code', () {
        final component = ComponentDefinition(
          name: 'AppButton',
          className: 'ButtonMeta',
          properties: const [
            ComponentProp(name: 'label', type: 'String', isRequired: true),
            ComponentProp(name: 'onPressed', type: 'VoidCallback?', isRequired: false),
          ],
          variants: const [],
        );

        final code = generator.generate(component: component);

        // Basic syntax checks
        expect(code, isNot(contains('  ,')));  // No trailing commas in wrong places
        expect(code, isNot(contains(';;')));   // No double semicolons
        expect(code.split('class AppButton').length, equals(2));  // Exactly one class declaration
      });
    });

    group('componentType', () {
      test('returns button', () {
        expect(generator.componentType, equals('button'));
      });
    });
  });
}
