include: package:lints/recommended.yaml

analyzer:
  plugins:
    - custom_lint

  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  errors:
    # Syntaxify custom lints - treat as errors
    empty_button_label: error
    invalid_callback_name: error
    empty_text_content: error
    empty_container: warning

linter:
  rules:
    # Standard Dart lints
    - avoid_print
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - unnecessary_const
    - unnecessary_new

# Custom lint configuration
custom_lint:
  # Enable Syntaxify lints for .screen.dart files
  enable_all_lint_rules: true
