include: package:lints/recommended.yaml

analyzer:
  plugins:
    - custom_lint

  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  errors:
    # Syntaxify custom lints - Empty values
    empty_button_label: error
    empty_text_content: error
    empty_icon_name: error
    empty_appbar_title: warning

    # Container checks
    empty_container: warning

    # Identifier validation
    invalid_callback_name: error

    # Number validation
    negative_number_value: error

    # Property conflicts
    conflicting_properties: info

    # Missing fields
    missing_textfield_label: warning

linter:
  rules:
    # Standard Dart lints
    - avoid_print
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - unnecessary_const
    - unnecessary_new

# Custom lint configuration
custom_lint:
  # Enable Syntaxify lints for .screen.dart files
  enable_all_lint_rules: true
