include: package:lints/recommended.yaml

analyzer:
  plugins:
    - custom_lint

  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  # Note: Custom lint codes are handled by custom_lint plugin, not analyzer
  # The following codes are defined in lib/src/lints/: empty_button_label, 
  # empty_text_content, empty_icon_name, etc.

linter:
  rules:
    # Standard Dart lints
    - avoid_print
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - unnecessary_const
    - unnecessary_new

# Custom lint configuration
custom_lint:
  # Enable Syntaxify lints for .screen.dart files
  enable_all_lint_rules: true
