// ============================================
// GENERATED BY SYNTAX v0.1.0
// DO NOT MODIFY - Regenerated on build
// Barrel file exporting all generated code
// ============================================

export 'generated/components/app_button.dart';
export 'generated/components/app_input.dart';
export 'generated/components/app_text.dart';
