import 'package:code_builder/code_builder.dart';
import 'package:dart_style/dart_style.dart';

import 'package:forge/src/models/token_definition.dart';

/// Generates AppTheme and AppThemeData for runtime token resolution.
///
/// Follows the pattern from meta_arch.dart:
/// - AppTheme is an InheritedWidget
/// - AppThemeData contains tokens for each component
/// - Factory constructors for each DesignStyle
class ThemeGenerator {
  ThemeGenerator({
    this.version = '0.1.0',
  });

  final String version;
  final _formatter = DartFormatter();
  final _emitter = DartEmitter(useNullSafetySyntax: true);

  /// Generate theme files for all components
  String generate({
    required List<TokenDefinition> tokens,
  }) {
    final library = Library(
      (b) => b
        ..comments.addAll(_generateHeader())
        ..directives.addAll(_generateImports(tokens))
        ..body.addAll([
          _generateDesignStyleEnum(),
          _generateAppThemeData(tokens),
          _generateAppTheme(),
        ]),
    );

    final code = library.accept(_emitter).toString();
    return _formatter.format(code);
  }

  List<String> _generateHeader() {
    return [
      '============================================',
      'GENERATED BY FORGE v$version',
      'DO NOT MODIFY - Regenerated on build',
      'Theme provider for Forge components',
      'Generated: ${DateTime.now().toIso8601String()}',
      '============================================',
    ];
  }

  Iterable<Directive> _generateImports(List<TokenDefinition> tokens) {
    final imports = <Directive>[
      Directive.import('package:flutter/material.dart'),
    ];

    // Import token files
    for (final token in tokens) {
      final componentName = token.componentName.toLowerCase();
      imports.add(Directive.import('../tokens/${componentName}_tokens.dart'));
    }

    return imports;
  }

  Enum _generateDesignStyleEnum() {
    return Enum(
      (b) => b
        ..name = 'DesignStyle'
        ..values.addAll([
          EnumValue((v) => v..name = 'material'),
          EnumValue((v) => v..name = 'cupertino'),
          EnumValue((v) => v..name = 'neo'),
        ]),
    );
  }

  Class _generateAppThemeData(List<TokenDefinition> tokens) {
    final fields = <Field>[];
    final constructorParams = <Parameter>[];
    final factoryMaterialArgs = <String>[];
    final factoryCupertinoArgs = <String>[];
    final factoryNeoArgs = <String>[];

    for (final token in tokens) {
      final componentName = token.componentName.toLowerCase();
      final tokensClassName = '${token.componentName}Tokens';

      fields.add(Field(
        (b) => b
          ..name = componentName
          ..type = refer(tokensClassName)
          ..modifier = FieldModifier.final$,
      ));

      constructorParams.add(Parameter(
        (b) => b
          ..name = componentName
          ..named = true
          ..required = true
          ..toThis = true,
      ));

      factoryMaterialArgs
          .add('$componentName: ${tokensClassName}Library.material()');
      factoryCupertinoArgs
          .add('$componentName: ${tokensClassName}Library.cupertino()');
      factoryNeoArgs.add('$componentName: ${tokensClassName}Library.neo()');
    }

    return Class(
      (b) => b
        ..name = 'AppThemeData'
        ..fields.addAll(fields)
        ..constructors.addAll([
          Constructor(
            (c) => c
              ..constant = true
              ..optionalParameters.addAll(constructorParams),
          ),
          Constructor(
            (c) => c
              ..factory = true
              ..name = 'material'
              ..lambda = true
              ..body = Code('AppThemeData(${factoryMaterialArgs.join(', ')})'),
          ),
          Constructor(
            (c) => c
              ..factory = true
              ..name = 'cupertino'
              ..lambda = true
              ..body = Code('AppThemeData(${factoryCupertinoArgs.join(', ')})'),
          ),
          Constructor(
            (c) => c
              ..factory = true
              ..name = 'neo'
              ..lambda = true
              ..body = Code('AppThemeData(${factoryNeoArgs.join(', ')})'),
          ),
          Constructor(
            (c) => c
              ..factory = true
              ..name = 'forStyle'
              ..requiredParameters.add(Parameter(
                (p) => p
                  ..name = 'style'
                  ..type = refer('DesignStyle'),
              ))
              ..body = Code('''
switch (style) {
  case DesignStyle.material:
    return AppThemeData.material();
  case DesignStyle.cupertino:
    return AppThemeData.cupertino();
  case DesignStyle.neo:
    return AppThemeData.neo();
}
'''),
          ),
        ]),
    );
  }

  Class _generateAppTheme() {
    return Class(
      (b) => b
        ..name = 'AppTheme'
        ..extend = refer('InheritedWidget')
        ..fields.add(Field(
          (f) => f
            ..name = 'data'
            ..type = refer('AppThemeData')
            ..modifier = FieldModifier.final$,
        ))
        ..constructors.add(Constructor(
          (c) => c
            ..constant = true
            ..optionalParameters.addAll([
              Parameter(
                (p) => p
                  ..name = 'super.key'
                  ..named = true,
              ),
              Parameter(
                (p) => p
                  ..name = 'data'
                  ..named = true
                  ..required = true
                  ..toThis = true,
              ),
              Parameter(
                (p) => p
                  ..name = 'super.child'
                  ..named = true
                  ..required = true,
              ),
            ]),
        ))
        ..methods.addAll([
          Method(
            (m) => m
              ..static = true
              ..name = 'of'
              ..returns = refer('AppThemeData')
              ..requiredParameters.add(Parameter(
                (p) => p
                  ..name = 'context'
                  ..type = refer('BuildContext'),
              ))
              ..body = Code('''
final theme = context.dependOnInheritedWidgetOfExactType<AppTheme>();
assert(theme != null, 'No AppTheme found in context. Wrap your app with AppTheme.');
return theme!.data;
'''),
          ),
          Method(
            (m) => m
              ..annotations.add(refer('override'))
              ..name = 'updateShouldNotify'
              ..returns = refer('bool')
              ..requiredParameters.add(Parameter(
                (p) => p
                  ..name = 'oldWidget'
                  ..covariant = true
                  ..type = refer('AppTheme'),
              ))
              ..body = Code('return data != oldWidget.data;'),
          ),
        ]),
    );
  }
}
