import 'package:code_builder/code_builder.dart';
import 'package:dart_style/dart_style.dart';

import 'package:syntaxify/src/models/token_definition.dart';

/// Generates AppTheme InheritedWidget that uses sealed DesignStyle pattern.
///
/// The generated code:
/// - Uses sealed DesignStyle for exhaustive style matching
/// - AppTheme holds a DesignStyle instance
/// - Widgets access tokens via AppTheme.of(context).style.button
class ThemeGenerator {
  ThemeGenerator({
    this.version = '0.1.0',
  });

  final String version;
  final _formatter =
      DartFormatter(languageVersion: DartFormatter.latestLanguageVersion);
  final _emitter = DartEmitter(useNullSafetySyntax: true);

  /// Generate app_theme.dart using sealed DesignStyle pattern
  String generate({
    required List<TokenDefinition> tokens,
  }) {
    final library = Library(
      (b) => b
        ..comments.addAll(_generateHeader())
        ..directives.addAll(_generateImports(tokens))
        ..body.addAll([
          _generateAppTheme(),
        ]),
    );

    final code = library.accept(_emitter).toString();
    return _formatter.format(code);
  }

  List<String> _generateHeader() {
    return [
      '============================================',
      'GENERATED BY SYNTAXIFY v$version',
      'DO NOT MODIFY - Regenerated on build',
      'Theme provider using sealed DesignStyle pattern',
      'Generated: ${DateTime.now().toIso8601String()}',
      '============================================',
    ];
  }

  Iterable<Directive> _generateImports(List<TokenDefinition> tokens) {
    return [
      Directive.import('package:flutter/material.dart'),
      Directive.import('../design_system.dart'),
    ];
  }

  Class _generateAppTheme() {
    return Class(
      (b) => b
        ..docs.add(
            '/// Syntaxify theme provider using sealed DesignStyle pattern.')
        ..docs.add('///')
        ..docs.add('/// Usage:')
        ..docs.add('/// ```dart')
        ..docs.add('/// AppTheme(')
        ..docs.add('///   style: MaterialStyle(),')
        ..docs.add('///   child: MyApp(),')
        ..docs.add('/// )')
        ..docs.add('/// ```')
        ..docs.add('///')
        ..docs.add('/// Access tokens:')
        ..docs.add('/// ```dart')
        ..docs
            .add('/// final buttonTokens = AppTheme.of(context).style.button;')
        ..docs.add('/// ```')
        ..name = 'AppTheme'
        ..extend = refer('InheritedWidget')
        ..fields.add(Field(
          (f) => f
            ..docs.add('/// The design style providing all component tokens.')
            ..name = 'style'
            ..type = refer('DesignStyle')
            ..modifier = FieldModifier.final$,
        ))
        ..constructors.add(Constructor(
          (c) => c
            ..constant = true
            ..optionalParameters.addAll([
              Parameter(
                (p) => p
                  ..name = 'super.key'
                  ..named = true,
              ),
              Parameter(
                (p) => p
                  ..name = 'style'
                  ..named = true
                  ..required = true
                  ..toThis = true,
              ),
              Parameter(
                (p) => p
                  ..name = 'super.child'
                  ..named = true
                  ..required = true,
              ),
            ]),
        ))
        ..methods.addAll([
          Method(
            (m) => m
              ..docs.add('/// Get the current [AppTheme] from the widget tree.')
              ..docs.add('///')
              ..docs.add('/// Throws if no [AppTheme] is found in the tree.')
              ..static = true
              ..name = 'of'
              ..returns = refer('AppTheme')
              ..requiredParameters.add(Parameter(
                (p) => p
                  ..name = 'context'
                  ..type = refer('BuildContext'),
              ))
              ..body = Code('''
final theme = context.dependOnInheritedWidgetOfExactType<AppTheme>();
assert(theme != null, 'No AppTheme found in context. Wrap your app with AppTheme.');
return theme!;
'''),
          ),
          Method(
            (m) => m
              ..annotations.add(refer('override'))
              ..name = 'updateShouldNotify'
              ..returns = refer('bool')
              ..requiredParameters.add(Parameter(
                (p) => p
                  ..name = 'oldWidget'
                  ..covariant = true
                  ..type = refer('AppTheme'),
              ))
              ..body = Code('return style != oldWidget.style;'),
          ),
        ]),
    );
  }
}
