import 'package:code_builder/code_builder.dart';
import 'package:dart_style/dart_style.dart';

import 'package:forge/src/core/interfaces/component_generator.dart';
import 'package:forge/src/models/ast_node.dart';
import 'package:forge/src/models/token_definition.dart';

/// Button-specific generator with renderer pattern and variants.
///
/// Generates AppButton widget that:
/// - Defines WHAT (props, variants)
/// - Delegates HOW to DesignStyle.renderButton()
class ButtonGenerator implements ComponentGenerator {
  ButtonGenerator({
    this.version = '0.1.0',
  });

  final String version;
  final _formatter = DartFormatter();
  final _emitter = DartEmitter(useNullSafetySyntax: true);

  @override
  String get componentType => 'button';

  @override
  bool canHandle(AstNode node) {
    final componentName = node.className.replaceAll('Meta', '').toLowerCase();
    return componentName == componentType;
  }

  @override
  String generate({
    required AstNode node,
    TokenDefinition? tokens,
  }) {
    final library = Library(
      (b) => b
        ..comments.addAll(_generateHeader(node))
        ..directives.addAll(_generateImports())
        ..body.addAll([
          _generateButtonClass(node),
        ]),
    );

    final code = library.accept(_emitter).toString();
    return _formatter.format(code);
  }

  List<String> _generateHeader(AstNode node) {
    return [
      '============================================',
      'GENERATED BY FORGE v$version',
      'DO NOT MODIFY - Regenerated on build',
      'Component: Button (Renderer Pattern)',
      'Generated: ${DateTime.now().toIso8601String()}',
      '============================================',
    ];
  }

  Iterable<Directive> _generateImports() {
    return [
      Directive.import('package:flutter/material.dart'),
      Directive.import(
          '../../design_system/design_system.dart'), // Barrel: AppTheme, DesignStyle, styles
    ];
  }

  Class _generateButtonClass(AstNode node) {
    return Class(
      (b) => b
        ..docs.add('/// A customizable button component.')
        ..docs.add('///')
        ..docs.add('/// Uses the renderer pattern: WHAT is defined here,')
        ..docs.add('/// HOW is delegated to [DesignStyle.renderButton].')
        ..docs.add('///')
        ..docs.add('/// Usage:')
        ..docs.add('/// ```dart')
        ..docs.add("/// AppButton.primary(label: 'Submit', onPressed: () {})")
        ..docs.add("/// AppButton.outlined(label: 'Cancel', onPressed: () {})")
        ..docs.add('/// ```')
        ..name = 'AppButton'
        ..extend = refer('StatelessWidget')
        ..fields.addAll(_generateFields(node))
        ..constructors.addAll(_generateConstructors(node))
        ..methods.add(_generateBuildMethod()),
    );
  }

  Iterable<Field> _generateFields(AstNode node) {
    return [
      Field(
        (b) => b
          ..docs.add('/// The button label text.')
          ..name = 'label'
          ..type = refer('String')
          ..modifier = FieldModifier.final$,
      ),
      Field(
        (b) => b
          ..docs.add('/// Callback when button is pressed.')
          ..name = 'onPressed'
          ..type = refer('VoidCallback?')
          ..modifier = FieldModifier.final$,
      ),
      Field(
        (b) => b
          ..docs.add('/// The button variant (primary, secondary, outlined).')
          ..name = 'variant'
          ..type = refer('ButtonVariant')
          ..modifier = FieldModifier.final$,
      ),
      Field(
        (b) => b
          ..docs.add('/// Whether the button shows loading state.')
          ..name = 'isLoading'
          ..type = refer('bool')
          ..modifier = FieldModifier.final$,
      ),
      Field(
        (b) => b
          ..docs.add('/// Whether the button is disabled.')
          ..name = 'isDisabled'
          ..type = refer('bool')
          ..modifier = FieldModifier.final$,
      ),
    ];
  }

  Iterable<Constructor> _generateConstructors(AstNode node) {
    return [
      // Main constructor
      Constructor(
        (c) => c
          ..constant = true
          ..optionalParameters.addAll([
            Parameter((p) => p
              ..name = 'super.key'
              ..named = true),
            Parameter((p) => p
              ..name = 'label'
              ..named = true
              ..required = true
              ..toThis = true),
            Parameter((p) => p
              ..name = 'onPressed'
              ..named = true
              ..toThis = true),
            Parameter((p) => p
              ..name = 'variant'
              ..named = true
              ..toThis = true
              ..defaultTo = const Code('ButtonVariant.primary')),
            Parameter((p) => p
              ..name = 'isLoading'
              ..named = true
              ..toThis = true
              ..defaultTo = const Code('false')),
            Parameter((p) => p
              ..name = 'isDisabled'
              ..named = true
              ..toThis = true
              ..defaultTo = const Code('false')),
          ]),
      ),
      // .primary() convenience constructor
      Constructor(
        (c) => c
          ..constant = true
          ..name = 'primary'
          ..docs.add('/// Primary button variant (emphasized).')
          ..optionalParameters.addAll([
            Parameter((p) => p
              ..name = 'super.key'
              ..named = true),
            Parameter((p) => p
              ..name = 'label'
              ..named = true
              ..required = true
              ..toThis = true),
            Parameter((p) => p
              ..name = 'onPressed'
              ..named = true
              ..toThis = true),
            Parameter((p) => p
              ..name = 'isLoading'
              ..named = true
              ..toThis = true
              ..defaultTo = const Code('false')),
            Parameter((p) => p
              ..name = 'isDisabled'
              ..named = true
              ..toThis = true
              ..defaultTo = const Code('false')),
          ])
          ..initializers.add(const Code('variant = ButtonVariant.primary')),
      ),
      // .secondary() convenience constructor
      Constructor(
        (c) => c
          ..constant = true
          ..name = 'secondary'
          ..docs.add('/// Secondary button variant (less emphasis).')
          ..optionalParameters.addAll([
            Parameter((p) => p
              ..name = 'super.key'
              ..named = true),
            Parameter((p) => p
              ..name = 'label'
              ..named = true
              ..required = true
              ..toThis = true),
            Parameter((p) => p
              ..name = 'onPressed'
              ..named = true
              ..toThis = true),
            Parameter((p) => p
              ..name = 'isLoading'
              ..named = true
              ..toThis = true
              ..defaultTo = const Code('false')),
            Parameter((p) => p
              ..name = 'isDisabled'
              ..named = true
              ..toThis = true
              ..defaultTo = const Code('false')),
          ])
          ..initializers.add(const Code('variant = ButtonVariant.secondary')),
      ),
      // .outlined() convenience constructor
      Constructor(
        (c) => c
          ..constant = true
          ..name = 'outlined'
          ..docs.add('/// Outlined button variant (transparent background).')
          ..optionalParameters.addAll([
            Parameter((p) => p
              ..name = 'super.key'
              ..named = true),
            Parameter((p) => p
              ..name = 'label'
              ..named = true
              ..required = true
              ..toThis = true),
            Parameter((p) => p
              ..name = 'onPressed'
              ..named = true
              ..toThis = true),
            Parameter((p) => p
              ..name = 'isLoading'
              ..named = true
              ..toThis = true
              ..defaultTo = const Code('false')),
            Parameter((p) => p
              ..name = 'isDisabled'
              ..named = true
              ..toThis = true
              ..defaultTo = const Code('false')),
          ])
          ..initializers.add(const Code('variant = ButtonVariant.outlined')),
      ),
    ];
  }

  Method _generateBuildMethod() {
    return Method(
      (m) => m
        ..annotations.add(refer('override'))
        ..name = 'build'
        ..returns = refer('Widget')
        ..requiredParameters.add(Parameter(
          (p) => p
            ..name = 'context'
            ..type = refer('BuildContext'),
        ))
        ..body = const Code('''
// Delegate to style's renderer (HOW)
return AppTheme.of(context).style.renderButton(
  label: label,
  variant: variant,
  onPressed: onPressed,
  isLoading: isLoading,
  isDisabled: isDisabled,
);
'''),
    );
  }
}
