import 'package:code_builder/code_builder.dart';
import 'package:dart_style/dart_style.dart';

import 'package:forge/src/core/interfaces/component_generator.dart';
import 'package:forge/src/models/ast_node.dart';
import 'package:forge/src/models/token_definition.dart';

/// Fallback generator for components without a specific generator.
///
/// Produces a basic widget structure that can be customized.
class GenericGenerator implements ComponentGenerator {
  GenericGenerator({
    this.version = '0.1.0',
  });

  final String version;
  final _formatter = DartFormatter();
  final _emitter = DartEmitter(useNullSafetySyntax: true);

  @override
  String get componentType => 'generic';

  @override
  bool canHandle(AstNode node) => true; // Handles everything

  @override
  String generate({
    required AstNode node,
    TokenDefinition? tokens,
  }) {
    final componentName = node.className.replaceAll('Meta', '');
    final className = 'App$componentName';
    final tokenName = componentName.toLowerCase();

    final library = Library(
      (b) => b
        ..comments.addAll(_generateHeader(componentName))
        ..directives.addAll(_generateImports())
        ..body.add(_generateWidgetClass(node, className, tokenName)),
    );

    final code = library.accept(_emitter).toString();
    return _formatter.format(code);
  }

  List<String> _generateHeader(String componentName) {
    return [
      '============================================',
      'GENERATED BY FORGE v$version',
      'DO NOT MODIFY - Regenerated on build',
      'Component: $componentName',
      'Generated: ${DateTime.now().toIso8601String()}',
      '============================================',
    ];
  }

  Iterable<Directive> _generateImports() {
    return [
      Directive.import('package:flutter/material.dart'),
      Directive.import('../theme/app_theme.dart'),
    ];
  }

  Class _generateWidgetClass(
    AstNode node,
    String className,
    String tokenName,
  ) {
    return Class(
      (b) => b
        ..name = className
        ..docs.add('/// Generated $className component.')
        ..extend = refer('StatelessWidget')
        ..fields.addAll(_generateFields(node))
        ..constructors.add(_generateConstructor(node))
        ..methods.add(_generateBuildMethod(node, tokenName)),
    );
  }

  Iterable<Field> _generateFields(AstNode node) {
    final fields = <Field>[];

    for (final prop in node.properties) {
      final typeStr = prop.isRequired
          ? prop.type
          : prop.type.endsWith('?')
              ? prop.type
              : '${prop.type}?';

      fields.add(Field(
        (b) => b
          ..name = prop.name
          ..modifier = FieldModifier.final$
          ..type = refer(typeStr),
      ));
    }

    return fields;
  }

  Constructor _generateConstructor(AstNode node) {
    final params = <Parameter>[];

    params.add(Parameter(
      (b) => b
        ..named = true
        ..name = 'super.key',
    ));

    for (final prop in node.properties) {
      params.add(Parameter(
        (b) => b
          ..named = true
          ..required = prop.isRequired
          ..toThis = true
          ..name = prop.name
          ..defaultTo =
              prop.defaultValue != null ? Code(prop.defaultValue!) : null,
      ));
    }

    return Constructor(
      (b) => b
        ..constant = true
        ..optionalParameters.addAll(params),
    );
  }

  Method _generateBuildMethod(AstNode node, String tokenName) {
    final body = '''
      final tokens = AppTheme.of(context).$tokenName;
      
      return Container(
        padding: tokens.padding,
        decoration: BoxDecoration(
          color: tokens.bgColor,
          borderRadius: BorderRadius.circular(tokens.radius),
        ),
        child: const Text('$tokenName component'),
      );
    ''';

    return Method(
      (b) => b
        ..annotations.add(refer('override'))
        ..name = 'build'
        ..returns = refer('Widget')
        ..requiredParameters.add(Parameter(
          (p) => p
            ..name = 'context'
            ..type = refer('BuildContext'),
        ))
        ..body = Code(body),
    );
  }
}
