import 'package:code_builder/code_builder.dart';
import 'package:dart_style/dart_style.dart';

import 'package:forge/src/core/interfaces/component_generator.dart';
import 'package:forge/src/models/ast_node.dart';
import 'package:forge/src/models/token_definition.dart';

/// Input-specific generator acting as a template for AppInput.
class InputGenerator implements ComponentGenerator {
  InputGenerator({
    this.version = '0.1.0',
  });

  final String version;
  final _formatter = DartFormatter();
  final _emitter = DartEmitter(useNullSafetySyntax: true);

  @override
  String get componentType => 'input';

  @override
  bool canHandle(AstNode node) {
    final componentName = node.className.replaceAll('Meta', '').toLowerCase();
    return componentName == componentType;
  }

  @override
  String generate({
    required AstNode node,
    TokenDefinition? tokens,
  }) {
    final library = Library(
      (b) => b
        ..comments.addAll(_generateHeader(node))
        ..directives.addAll(_generateImports())
        ..body.addAll([
          _generateInputClass(node),
        ]),
    );

    final code = library.accept(_emitter).toString();
    return _formatter.format(code);
  }

  List<String> _generateHeader(AstNode node) {
    return [
      '============================================',
      'GENERATED BY FORGE v$version',
      'DO NOT MODIFY - Regenerated on build',
      'Component: Input (TextField)',
      'Generated: ${DateTime.now().toIso8601String()}',
      '============================================',
    ];
  }

  Iterable<Directive> _generateImports() {
    return [
      Directive.import('package:flutter/material.dart'),
      Directive.import('../../design_system/design_system.dart'),
    ];
  }

  Class _generateInputClass(AstNode node) {
    return Class(
      (b) => b
        ..docs.add('/// A customizable input component.')
        ..docs.add('///')
        ..docs.add('/// Delegates rendering to [DesignStyle.renderInput].')
        ..name = 'AppInput'
        ..extend = refer('StatelessWidget')
        ..fields.addAll(_generateFields())
        ..constructors.add(_generateConstructor())
        ..methods.add(_generateBuildMethod()),
    );
  }

  Iterable<Field> _generateFields() {
    return [
      Field((b) => b
        ..name = 'controller'
        ..type = refer('TextEditingController?')
        ..modifier = FieldModifier.final$),
      Field((b) => b
        ..name = 'label'
        ..type = refer('String?')
        ..modifier = FieldModifier.final$),
      Field((b) => b
        ..name = 'hint'
        ..type = refer('String?')
        ..modifier = FieldModifier.final$),
      Field((b) => b
        ..name = 'errorText'
        ..type = refer('String?')
        ..modifier = FieldModifier.final$),
      Field((b) => b
        ..name = 'obscureText'
        ..type = refer('bool')
        ..modifier = FieldModifier.final$),
      Field((b) => b
        ..name = 'enabled'
        ..type = refer('bool')
        ..modifier = FieldModifier.final$),
      Field((b) => b
        ..name = 'onChanged'
        ..type = refer('ValueChanged<String>?')
        ..modifier = FieldModifier.final$),
      Field((b) => b
        ..name = 'onSubmitted'
        ..type = refer('ValueChanged<String>?')
        ..modifier = FieldModifier.final$),
      Field((b) => b
        ..name = 'prefixIcon'
        ..type = refer('String?')
        ..modifier = FieldModifier.final$),
      Field((b) => b
        ..name = 'suffixIcon'
        ..type = refer('String?')
        ..modifier = FieldModifier.final$),
      Field((b) => b
        ..name = 'onTapPrefix'
        ..type = refer('VoidCallback?')
        ..modifier = FieldModifier.final$),
      Field((b) => b
        ..name = 'onTapSuffix'
        ..type = refer('VoidCallback?')
        ..modifier = FieldModifier.final$),
    ];
  }

  Constructor _generateConstructor() {
    return Constructor(
      (c) => c
        ..constant = true
        ..optionalParameters.addAll([
          Parameter((p) => p
            ..name = 'super.key'
            ..named = true),
          Parameter((p) => p
            ..name = 'controller'
            ..named = true
            ..toThis = true),
          Parameter((p) => p
            ..name = 'label'
            ..named = true
            ..toThis = true),
          Parameter((p) => p
            ..name = 'hint'
            ..named = true
            ..toThis = true),
          Parameter((p) => p
            ..name = 'errorText'
            ..named = true
            ..toThis = true),
          Parameter((p) => p
            ..name = 'obscureText'
            ..named = true
            ..toThis = true
            ..defaultTo = const Code('false')),
          Parameter((p) => p
            ..name = 'enabled'
            ..named = true
            ..toThis = true
            ..defaultTo = const Code('true')),
          Parameter((p) => p
            ..name = 'onChanged'
            ..named = true
            ..toThis = true),
          Parameter((p) => p
            ..name = 'onSubmitted'
            ..named = true
            ..toThis = true),
          Parameter((p) => p
            ..name = 'prefixIcon'
            ..named = true
            ..toThis = true),
          Parameter((p) => p
            ..name = 'suffixIcon'
            ..named = true
            ..toThis = true),
          Parameter((p) => p
            ..name = 'onTapPrefix'
            ..named = true
            ..toThis = true),
          Parameter((p) => p
            ..name = 'onTapSuffix'
            ..named = true
            ..toThis = true),
        ]),
    );
  }

  Method _generateBuildMethod() {
    return Method(
      (m) => m
        ..annotations.add(refer('override'))
        ..name = 'build'
        ..returns = refer('Widget')
        ..requiredParameters.add(Parameter(
          (p) => p
            ..name = 'context'
            ..type = refer('BuildContext'),
        ))
        ..body = const Code('''
        return AppTheme.of(context).style.renderInput(
          controller: controller,
          label: label,
          hint: hint,
          errorText: errorText,
          obscureText: obscureText,
          enabled: enabled,
          onChanged: onChanged,
          onSubmitted: onSubmitted,
          prefixIconName: prefixIcon,
          suffixIconName: suffixIcon,
          onTapPrefix: onTapPrefix,
          onTapSuffix: onTapSuffix,
        );
        '''),
    );
  }
}
